### ISSUE TITLE
Retool Ovationtix Skins

### ISSUE THREAD

**Issue by marcguyer** [bppwrite/bppwrite.github.io#13]
This is something the Ovationtix people have to do. The current version is horrible but hopefully they have improved a bit since the old site with responsive/mobile versions of the pages. An email to support@ovationtix.com should get this going. Probably have to wait until after the site is launched but it wouldn't hurt to see if they can do it in advance based on the http://bppwrite.github.io site.

**Comment by jessicareed** [comment]
I've reached out to Ovationtix about this!

**Comment by marcguyer** [comment]
Me too, this morning but they have not yet responded.

**Comment by marcguyer** [comment]
The Ovationtix ticket for this is here:

http://ovationtix.zendesk.com/hc/requests/30599

**Comment by marcguyer** [comment]
This is ready for launch. We'll just need to tell them to install it when we're ready.

**Comment by marcguyer** [comment]
Their skin is ugly as hell. It's like they viewed it in Internet Explorer 6, took a screenshot, cut it up in MS Paint and loaded it into some sort of antiquated wrapper. The slide menu is inoperable and the typography looks terrible. 

Reportedly, they have a new responsive layout coming someday. It's available to some of their clients but BCT is using too many advanced features that aren't available yet in the new version. I suggest that we ask them to use their default skin instead, or whatever the BCT default is, until the new version is available.

**Comment by marcguyer** [comment]
BCT default is enabled. Closing.
