### ISSUE TITLE
After cloning, the menu doesn't work

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#19]
@mattbatman, @marcguyer said that the javascript needs to compile somehow after a clone (and probably after a pull, etc). Or something....

**Comment by mattbatman** [comment]
I'm just testing this now: it's when you clone everything and are trying to work locally (ie. `hugo serve`) that it won't work. The menu still works when you push your changes to the site after a clone. To get it to work locally, there's a few more things you'd have to install.

I think the best solution in the short-term is treat our JavaScript like the sass/CSS/styles: force someone who makes changes to manually compile the files and commit them. That way, you @jessicareed, wouldn't need to do anything more.

With our current setup, to get the menu to work locally, you'd have to follow the steps I've pasted below (install nodejs, run `npm install`, run `npm install jspm -g`, run `jspm install`).

## INSTALLATIONS REQUIRED TO GET THE MENU TO WORK OFFLINE
1. Install Node

  Go to [nodejs.org](https://nodejs.org/en/) and install the latest stable version of node recommended for you. There should be a big green button on the home page.

2. Install Dependencies with NPM

  If you completed step one and installed Node, NPM was automatically installed on your computer. Now, you need to use NPM to install our dependencies (these are listed in the `package.json` file for this project, if you're curious).

  First, navigate to the root directory for this project (ie. "wherever-you-cloned-it" or "wherever-package.json-lives"). Second, you'll run `npm install`.

  ```sh
  cd ~/wherever-you-cloned-it
  npm install
  ```

3. Install jspm (and Some More Dependencies)

  jspm is used to bundle the JavaScript we write with the third-party libraries we use into one file for deployment. It's also used to install those third-party libraries.

  First, you need to install the jspm command line interface on your computer

  ```sh
  npm install jspm -g
  ```

  Next, you need to install some more third-party JavaScript libraries using jspm

  ```sh
  jspm install
  ```

**Comment by mattbatman** [comment]
Another option could be to replace [everything in here](https://github.com/bppwrite/bppwrite.github.io/blob/dev/layouts/partials/body_script.html#L11) with CDN deliveries for SystemJS, RxJS, and Slideout.

**Comment by mattbatman** [comment]
@jessicareed When you have your GitHub Desktop thing open, look for "Repository" at the top menu of your screen and select "Pull." That should update your copy of the files and everything should work now.

![artboard 1](https://cloud.githubusercontent.com/assets/8661427/22307155/ffa86166-e30f-11e6-96ae-4e4c8a5f9cc4.png)

**Comment by marcguyer** [comment]
@mattbatman Is this how it's going to be long-term?

**Comment by mattbatman** [comment]
I think so.

The alternative is to require Node.js as a dependency for everyone. They'd probably have to run at least one script after cloning. From there, there's an npm package I've found that integrates scripts with Git hooks. So, a script could probably rebuild everything on `git pull`.
