### ISSUE TITLE
Replacing PlayOffs show image on season page

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#21]
I need to replace the PlayOffs image on the Season page (and then I suppose on the actual show page for continuity's sake). I see the "Create a poster" instructions, but am not confident that I know how to make all the changes in the correct area. Please advise or point me in the right direction, thanks!

**Comment by marcguyer** [comment]
First, there is no such thing as updating content in multiple places in this architecture.

To do what you want, you *literally* only need to follow the [Add Poster](https://github.com/bppwrite/bppwrite.github.io/blob/dev/CONTRIBUTING.md#add-poster) section of the guide. You have the power.

**Comment by jessicareed** [comment]
Okay, I did that. That's it?

**Comment by marcguyer** [comment]
If you commit your change and sync, I'll be able to see to confirm. You may also run `hugo serve` locally as you've done before to see your modification before it becomes public.
