### ISSUE TITLE
Submit a Play page loading blank content

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#23]
The website is loading just fine for me. However, a playwright emailed me this morning to say that the Submit a Play link I sent her is "blank." She wrote: 

For some reason, that page comes up blank. I see the headings but when I click on "Submit a Play" I get the border with your sponsors listed but a blank center to the page. 

Not sure if this is worthy of creating an issue, but I wanted to make you guys aware of it incase it appears to be something on our end.

**Comment by marcguyer** [comment]
What is the "Submit a Play link I sent her"?

**Comment by jessicareed** [comment]
She emailed me saying the website wasn't loading, I sent her the link to the Submit a Play page. 

http://newplays.org/submit-a-play/#submit-a-play

**Comment by marcguyer** [comment]
We're missing some information here. We cannot replicate. I think she is going somewhere else. If you arrive at http://newplays.org/submit-a-play/#submit-a-play, there's no reason to "click on 'Submit a Play'". She's indicated that she arrives at the page, then clicks on "Submit a Play". It would be helpful if we could see a screenshot of the first thing she sees, then what she sees after clicking "Submit a Play". Or, what is the URL in the browser address bar when she's seeing the blank screen?

**Comment by jessicareed** [comment]
I will try to get clarification but I suspect that providing a screenshot is beyond her capabilities.

**Comment by marcguyer** [comment]
Assuming this is resolved.
