### ISSUE TITLE
Special/New Works page

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#25]
For this page, there are 5 different heros but it appears that the only one visible is "hero Toast 1.jpg" I tried to fix it, got an error, am admitting that I have no idea what the issue is, or what I even did. I undid the commit. Sorry if I broke something. How can we make this special cycle through all 5 images?

**Comment by marcguyer** [comment]
@mattbatman I resolved this with https://github.com/bppwrite/bppwrite.github.io/compare/56b093dd60da23fe709ce5ad80da48e27879c41c...05a78a80dc61397efcdc01c24f8d8e2c39f04c64
