### ISSUE TITLE
SPUN date wrapping

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#26]
We added three additional show dates for SPUN and in the upper right on the show page, the dates are wrapping all funky. @mattbatman can you make this look prettier? It's here: 

http://newplays.org/show/2017-2018/spun/

**Comment by mattbatman** [comment]
I'm looking into fixing the alignment. A better solution, though, could be to separate months in the underlying template.

Instead of:
March and April
29 30 1 2

We'd have:
March
29 30
April
1 2
