### ISSUE TITLE
Deleting Sponsor Logos

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#28]
I need to remove some sponsor logos from the homepage - shall I just delete the main content file for the sponsors I need to remove or is there a better way?

**Comment by marcguyer** [comment]
Do the opposite of [creating a sponsor](https://github.com/bppwrite/bppwrite.github.io/blob/dev/CONTRIBUTING.md#creating-a-sponsor). Simply delete the directory that is named after the sponsor you want to remove.
