### ISSUE TITLE
Optimize Hero Image

### ISSUE THREAD

**Issue by marcguyer** [bppwrite/bppwrite.github.io#3]
The hero image is currently something like 22Mb. That's not ideal.

**Comment by marcguyer** [comment]
Turns out most of the images need some help. All of the hero images are huge. We're not "fine tuning" yet, but for now, let's just get them all down to a manageable size like you did with the main hero. Later, we can do some research on image optimization, responsiveness, retina screens, etc.

**Comment by mattbatman** [comment]
I've still been thinking of all the images as placeholders. Any image pulled from the flyer folder can be taken down in size pretty quickly in Photoshop by saving for web.

**Comment by marcguyer** [comment]
Understood but the index is >100Mb currently as a result of the size of the images resulting in extremely slow load, cumbersome cloning, etc.
