### ISSUE TITLE
Is there a way to link to a PDF? 

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#31]
I need to post a job opportunity and I'd like to do it on the Get Involved page. Can I link to a PDF of the job description rather than post the entirety of the content on the page? I've read some Github posts on markdown and linking, but don't know enough to make this happen. Is this something we can do?

**Comment by marcguyer** [comment]
Linking to a PDF is not appreciably different than linking to anything else. Look at the Musical Theater Camp content file "Register Now" link. That actually links to a PDF on the ivy tech site but you could put the PDF in the same dir as the content file and link to it like `[check out this job](pdf_filename.pdf)`.
