### ISSUE TITLE
Additional frontmatter for FRONT PAGE FLO

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#32]
I need to add frontmatter elements for FRONT PAGE FLO - in the billing section at the top of the show page, I need to add Directed By (there is a frontmatter element that has George Pinney's name, but it is not displaying with the rest of the information), Executive Producer, and Music Director. 

I added these elements to the archetype directory for shows, but when I went into the FLO directory, those elements were not there to be filled with content. Did I miss a step?

**Comment by marcguyer** [comment]
The archetype is only used when a show is created. So, changing the archetype would only affect creation of future shows. Further, the site was designed to only used the archetype data that was there when it was designed. You can see the logic for the byline here:

https://github.com/bppwrite/bppwrite.github.io/blob/dev/layouts/partials/show_or_event/byline.html

A musical byline is handled differently than for other genres. Notable is that "Directed by" isn't used at all for a musical. I'm guessing that's a bug... That could easily be fixed.

Regarding "Executive Producer" and "Musical Director", please describe how you'd like this to be displayed on the show page.

**Comment by jessicareed** [comment]
Ah, that makes sense, thank you. I would like it to display like this: 

Executive Producer Sara Kass
Music Director Terry LaBolt 

Thank you!

**Comment by marcguyer** [comment]
It's done. Take a look and see if anything needs to change.

**Comment by jessicareed** [comment]
It's perfect - thank you!
