### ISSUE TITLE
Loading the BPP Website as a project on Atom? 

### ISSUE THREAD

**Issue by jessicareed** [bppwrite/bppwrite.github.io#33]
I feel like I should know this, but I don't. I need to set up both Jana and Brad with access to the website via Atom and Github Desktop. How do they initially access the BPP Website project in Atom?

**Comment by jessicareed** [comment]
I may have found the answer - it's under the SETUP (install, clone, and run) instructions, yes?

**Comment by marcguyer** [comment]
Yes.
