### ISSUE TITLE
Style oddities on season page

### ISSUE THREAD

**Issue by marcguyer** [bppwrite/bppwrite.github.io#40]
Pull the [2019 branch](https://github.com/bppwrite/bppwrite.github.io/tree/2019) and you'll see that the season page has some dark text on a dark background that appears unintentional on the show cards.

<img width="314" alt="screen shot 2018-07-09 at 2 00 02 pm" src="https://user-images.githubusercontent.com/35496/42467669-86491f50-8380-11e8-96cc-ff1eb2176efa.png">

**Comment by mattbatman** [comment]
Do I need to do something besides just switching to the 2019 branch to see the 2018-2019 season page?

I think this also occurs on the current season page. Chad's name is always in purple. Also, the poster/card with Chad's name is not clickable in its entirety, the way the other cards are.

**Comment by JSurigao** [comment]
You're right, I never noticed it on the current season. 

I'm not sure how you need to view the 2019 branch. I'm hosting it locally and opening it from my terminal into a browser (that may not be what you mean). Maybe Marc can help with that part? Let me know if there's something I need to do from here so you can access it.

**Comment by mattbatman** [comment]
I can view the 2019 branch. I don't see the 2018-2019 season on the branch, and seem to get 404 errors when I try to manually manipulate the url. However, I don't really need to see the 2018-2019 season to fix this problem, because the same problem occurs in the current year. When I figure out what's different about the templating logic for "Chad situations," the styling issue will be fixed. There's something specifically strange about how we render the "directed by" attribute that throws everything off.

**Comment by mattbatman** [comment]
This should be fixed. I don't think that I created inadvertent bugs on other pages, but I want to look around for them.

**Comment by JSurigao** [comment]
@mattbatman It still looks the same for me on both the 2019 and live dev branch.

**Comment by JSurigao** [comment]
@mattbatman Hmm. Now all the text is black. See screen shot. Is this just on my screen?

![screen shot 2018-07-10 at 11 50 51 am](https://user-images.githubusercontent.com/33761733/42522759-f8e7a28e-8439-11e8-9f0f-01dcb7c23889.png)

**Comment by mattbatman** [comment]
@JSurigao could you copy and paste the URL of the page you're looking at? Is it http://localhost:1313/series/2018-2019/?

**Comment by JSurigao** [comment]
Yes: 
http://localhost:1313/series/2018-2019/

**Comment by JSurigao** [comment]
It's working now. I had to replace an image for one of the show, so I refreshed everything, opened it in a new terminal tab, and it's all fixed! 
![screen shot 2018-07-10 at 1 22 07 pm](https://user-images.githubusercontent.com/33761733/42526620-530569ae-8444-11e8-9dec-ae9dfb13234d.png)
