### ISSUE TITLE
Lead Sponsor 

### ISSUE THREAD

**Issue by marcguyer** [bppwrite/bppwrite.github.io#41]
Looks like we have another style oddity when a lead sponsor is enabled. The new lead sponsor is Cook. To replicate, set `is_lead = true` in the frontmatter of https://github.com/bppwrite/bppwrite.github.io/blob/2019/content/sponsor/cook-group/index.md. Here's a shot:

![screen shot 2018-07-09 at 10 47 09 am](https://user-images.githubusercontent.com/35496/42468087-d6486ab4-8381-11e8-830c-53c43eeae5ac.png)

**Comment by mattbatman** [comment]
See #29.
