### ISSUE TITLE
Index hero glitch

### ISSUE THREAD

**Issue by marcguyer** [bppwrite/bppwrite.github.io#47]
I thought we had this fixed but it remains an issue...

[Screen Recording 2019-05-31 at 10.03.09 AM.zip](https://github.com/bppwrite/bppwrite.github.io/files/3241522/Screen.Recording.2019-05-31.at.10.03.09.AM.zip)

Note how a white screen flashes for a moment when the site is loaded. This is reportedly the top priority fix.

**Comment by marcguyer** [comment]
@mattbatman Have you seen this?

**Comment by mattbatman** [comment]
@marcguyer Yes.

**Comment by mattbatman** [comment]
This is unrelated to the hero functionality, by the way. It's an unstyled flash of content. It happens on every page. It probably just looks the worst on the home page.

There's a lot of things that could be done to improve page speed. The most obvious is this [sponsor logo](https://github.com/bppwrite/bppwrite.github.io/blob/dev/content/sponsor/brown-county-community-foundation/logo.jpg) that's over 3 MB.

There's more to be done on trying to hide the nav markup that you see.

**Comment by marcguyer** [comment]
Yeah, good catch. I optimized that sponsor logo which does seem to help but the un-styled content still flashes.

**Comment by mattbatman** [comment]
The flash of unstyled content appears to be entirely fixed, once you clear cache.
