### ISSUE TITLE
Sass compile workflow

### ISSUE THREAD

**Issue by marcguyer** [bppwrite/bppwrite.github.io#5]
We need a dev workflow for sass compiling as well as maybe a step for wercker to do it on build. I think the result should be only `.css` files deployed to `/public` but that's not a hard requirement... Ideally it would be part of hugo but [that doesn't seem to be a thing (yet)](https://discuss.gohugo.io/t/support-for-html-css-js-preprocessors/127). So, I suppose for now, we can use Atom or whatever and the workflow will need to be documented in https://github.com/bppwrite/bppwrite.github.io/blob/dev/README.md.

**Comment by mattbatman** [comment]
So far, I've been using the command line to compile sass. I navigate to `static` and run
```
sass --watch scss:css
```
which watches the `scss` directory and compiles it to `css`. It plays nicely with hugo when you run ` hugo serve` from a different tab.

Do you think we might want to bother minifying our css? If so, we may want to start to consider using Gulp or NPM Scripts and incorporating our sass workflow into that.

Also, we're going to start to need JavaScript for a slider and probably the mobile navigation. It would be cool (but unnecessary) to write in ES2015 and compile it back to JS5 with [Babel](https://babeljs.io/), which could be incorporated into a Gulp/Grunt/NPM workflow.

**Comment by marcguyer** [comment]
Neato. Whatever you decide. Document it so anyone could do it. We'll need whatever it is to be added as a build step in our wercker flow. Might as well minify everything...

**Comment by marcguyer** [comment]
Is this done then?

**Comment by mattbatman** [comment]
It's done for now, at least.
